### PR TITLE
Update CircuitHUD-V2 to Factorio 2.0

### PR DESCRIPTION
**Pull request by hgschmie**
All the changes necessary to make CircuitHUD-V2 work with Factorio 2.0

Please let me know if you plan to do a release, otherwise I would create a fork (but would prefer not to).

### CODE REVIEW

**Comment by hgschmie** [comment]
with stdlib being dead / no longer maintained, I have a private fork that works with 2.0 that I use in my mods to replace stdlib. I put the code here as well; there are some efforts to create a "stdlib2" (and I contributed to it) but that seems to be not really moving forward. Hence pulling in the code and removing that dependency.

**Comment by JasonLandbridge** [comment]
@hgschmie Hey thank you so much! I have quit Factorio (too addicting) so I would be more than happy to make you a maintainer for this mod. If this PR is ready to go, then I will publish it as is

**Comment by JasonLandbridge** [comment]
I cleaned up the repo and deleted outdated branches, master should be the one with the latest data. I figured, let me try to add a GitHub action to make publishing easier but I can do it manually for now

**Comment by hgschmie** [comment]
I will fix the conflicts later today (after work). Happy to help maintain the mod / take over (I don't know how this would be done in the portal). 

I hear you on the "too addictive"; I use it as an escape valve for fun programming; pure playing has gotten a bit boring for me. Right now, I am fixing up all the mods that I need for my main play when migrating from 1.1 to 2.0

**Comment by hgschmie** [comment]
(I use the vscode / factorio dev kit tasks for publishing; never bothered much to automate this with github with my own mods).

**Comment by JasonLandbridge** [comment]
> I will fix the conflicts later today (after work). Happy to help maintain the mod / take over (I don't know how this would be done in the portal).

Great, I will add you to this repo! I don't think I can add you to the portal, but I have manged to setup a working publishing pipeline ([Factorio-mod-uploader-action](https://github.com/TheBrutalX/Factorio-mod-uploader-action)) so any push to master gets published to the portal. But you need to make sure to change the version numbering otherwise it overwrites the previous upload.

> I hear you on the "too addictive"; I use it as an escape valve for fun programming; pure playing has gotten a bit boring for me. Right now, I am fixing up all the mods that I need for my main play when migrating from 1.1 to 2.0

Yeah same, I sank in 1600 hours before I realized I need help :joy: Now I'm a recovering addict who works on open-source projects ([PlexRipper](https://github.com/PlexRipper/PlexRipper)) which seems to be more useful then growing the factory, again :P

**Comment by hgschmie** [comment]
alright, let's try that. What's the worst that can happen.

**Comment by JasonLandbridge** [comment]
@hgschmie Great it worked! https://mods.factorio.com/mod/CircuitHUD-V2/downloads

**Comment by emk** [comment]
This update is great!

One new feature that would be useful sooner or later is that all items now have a "quality". This is a 100% optional gameplay mechanic, but it's especially useful for modules and space platforms. So "common iron plates", "uncommon iron plates", "rare iron plates", etc., are all basically separate items.

There are two fixes which would be immediately useful here:

1. Display the "quality indicators" with signal icons.
2. Respect quality indicators of filters.

I'd be happy to try working on a PR if anyone is interested!

**Comment by JasonLandbridge** [comment]
@emk Sure go ahead! I haven't played the latest versions of Factorio, so I'm not sure what you mean but the more features the better :P

Also, kindly make a separate issue as not to hide discussions in closed PR's

**Pull request merged**
